name: 'Hello World'
author: Rodrigo Bernal
description: 'First action created for github using docker'
inputs:
  who-to-greet: # id of input
    description: 'Who to greet'
    required: true
    default: 'Rodrigo'
outputs:
  time: #id of input
    description: "The greeting time"
runs:
  using: "docker"
  image: "Dockerfile"
  # entrypoint:
  args:
    - ${{ inputs.who-to-greet }}
    