name: Actions-Workflow

on:
  push:
  #pull_request:
    branches:
      - master
      - 'feature/*' #Matches feature/featA
      - 'feature/**'
  # repository_dispatch:
  #   types: [build]
  # schedule:
  #   - cron: "0/5 * * * *"
  #   - cron: "0/7 * * * *"
  # push:
  # pull_request:
  #   types: [closed, assigned, opened, reopened]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello docker
        id: hello
        uses: ./.github/actions/hello-docker
#        with:      
#          who-to-greet: "World"
      - name: Show time
        run: echo "Time ${{ steps.hello.outputs.time }}"
