name: simple

on:
  push:
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls -l
          ./script.sh
      - name: Checkout
        if: always()
        uses: actions/checkout@v3
      - name: list files 2
        if: always()
        run: |
          pwd
          ls -l  
          ./script.sh
      - name: Hello docker
        if: always()
        id: hello
        uses: ./.github/actions/hello-docker