name: simple

on:
  push:
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls -l
      - name: Checkout
        uses: actions/checkout@v3
      - name: list files 2
        run: |
          pwd
          ls -l  
      - name: Hello docker
        id: hello
        uses: ./.github/actions/hello-docker